In [10]:
%matplotlib inline 
from __future__ import division

from numpy.random import randn
import numpy as np
from math import sqrt
np.set_printoptions(precision=4, suppress=True)

In [14]:
def dis(point):
    distance = np.zeros((len(point),len(point)))
    for i in range(0,len(point)):
        for j in range(0,len(point)):
            distance[i][j] = sqrt((point[i][0]-point[j][0])**2+(point[i][1]-point[j][1])**2)
            j = j+1
        i = i+1
    print(distance)

In [17]:
point = randn(6,2)
dis(point) #distance[i][j]表示point[i]与point[j]之间的距离

[[ 0.      1.9857  0.9158  1.4698  2.1732  0.5117]
 [ 1.9857  0.      1.2835  3.4545  0.3354  1.4825]
 [ 0.9158  1.2835  0.      2.291   1.3756  0.4779]
 [ 1.4698  3.4545  2.291   0.      3.6283  1.9734]
 [ 2.1732  0.3354  1.3756  3.6283  0.      1.6617]
 [ 0.5117  1.4825  0.4779  1.9734  1.6617  0.    ]]
