In [2]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [4]:
data = randn(20)
data.size
string = 'dad'
complexstr = np.identity(string)
complexstr

array('daddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddad', 
      dtype='<U60')

In [105]:
data = np.array(data)
record = []
i = 12
record.append(1)
record

[1]

In [107]:
for i in range(4,len(data)):
    if(data[i] > max(data[i-1:i]) and data[i] > max(data[i+1:i+2])):
        record.append(data[i]) 
print (record)

[1, 1.1001658701059516, 1.1501450724349334, 0.59293000650705108, 0.65205192851600524, 0.77437759031556586, 1.1001658701059516, -0.33365210412384083, 1.1501450724349334, 0.44762864092754351]


0
(array([0, 1, 2]), array([0, 0, 0]))
0
(array([0, 1, 2]), array([0, 0, 0]))
0
(array([0, 1, 2]), array([0, 0, 0]))
1
(array([3]), array([0]))
2
(array([4]), array([0]))
3
(array([5]), array([0]))
4
(array([6]), array([0]))
5
(array([7]), array([0]))
