In [146]:
###################################  PROBLEM 1 ##################################
from numpy.random import randn
import numpy  as np
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline
x = list(np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]))
num = len(x)
y=x[:]
##let y be a copy of x
def total_equal(a,b):
    flag = True
    Length_ab=min(len(a),len(b))
    for k in range(Length_ab):
            flag = flag * (a[k] == b[k])
    return flag
##a function to judge whether two list have the same value in all dimensions

In [147]:
a = np.zeros(num)
for k in range(num):
    for j in range(k,num):
        if total_equal(x[k],y[j]):
            a[k] = a[k] +1
print(a)
b=[]
for g in range(len(a)):
    if a[g] == 1:
        b.append(x[g])
##set a new list to cover all the unique elements
print(b)

[ 2.  2.  1.  1.]
[array([ 1.,  2.,  3.]), array([ 4.,  5.,  6.])]


In [148]:
###################################  PROBLEM 2 ##################################
z=np.array(range(20))
##initialize Z
v = np.zeros((len(z)-2,3))
##initialize our empty list
for k in range(len(z)-2):
    v[k]=z[k:k+3]
print(v)
##reset the list

[[  0.   1.   2.]
 [  1.   2.   3.]
 [  2.   3.   4.]
 [  3.   4.   5.]
 [  4.   5.   6.]
 [  5.   6.   7.]
 [  6.   7.   8.]
 [  7.   8.   9.]
 [  8.   9.  10.]
 [  9.  10.  11.]
 [ 10.  11.  12.]
 [ 11.  12.  13.]
 [ 12.  13.  14.]
 [ 13.  14.  15.]
 [ 14.  15.  16.]
 [ 15.  16.  17.]
 [ 16.  17.  18.]
 [ 17.  18.  19.]]
